version: '3.8'

services:
  postgres:
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=admin2002
      - POSTGRES_DB=postgres
    volumes:
      - postgres-data:/var/lib/postgresql/data
       
  pgadmin:
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=evarizm32@gmail.com
      - PGADMIN_DEFAULT_PASSWORD=admin2002
      - PGADMIN_LISTEN_PORT=8001
    ports:
      - "8001:8001"
    depends_on:
      - postgres

volumes:
  postgres-data:
